
version: '3.8'

services:
  web:
    build: .
    ports:
      - "9988:9988"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development